"""add premium start and expiry dates to user

Revision ID: 04dde523c3b0
Revises: cece949aa325
Create Date: 2025-07-09 10:45:26.050750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04dde523c3b0'
down_revision: Union[str, None] = 'cece949aa325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('premium_start_date', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('users', sa.Column('premium_expiry_date', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'premium_expiry_date')
    op.drop_column('users', 'premium_start_date')
    # ### end Alembic commands ###
