"""Add coingecko fallback fields to alert model

Revision ID: def04717d8d0
Revises: 36934e6acbf5
Create Date: 2025-07-09 00:04:12.571116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'def04717d8d0'
down_revision: Union[str, None] = '36934e6acbf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('source', sa.String(length=50), server_default='cmc', nullable=False))
    op.add_column('alerts', sa.Column('token_address', sa.String(length=255), nullable=True))
    op.add_column('alerts', sa.Column('network_id', sa.String(length=100), nullable=True))
    op.add_column('alerts', sa.Column('polling_interval_seconds', sa.Integer(), nullable=True))
    op.alter_column('alerts', 'cmc_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('idx_alerts_active_cmc_id', table_name='alerts', postgresql_where="((alert_type)::text = 'token_price'::text)")
    op.create_index('idx_alerts_active_cmc', 'alerts', ['is_active', 'source', 'cmc_id'], unique=False, postgresql_where=sa.text("alert_type = 'token_price' AND source = 'cmc'"))
    op.create_index('idx_alerts_active_coingecko', 'alerts', ['is_active', 'source'], unique=False, postgresql_where=sa.text("alert_type = 'token_price' AND source = 'coingecko'"))
    op.create_index(op.f('ix_alerts_network_id'), 'alerts', ['network_id'], unique=False)
    op.create_index(op.f('ix_alerts_source'), 'alerts', ['source'], unique=False)
    op.create_index(op.f('ix_alerts_token_address'), 'alerts', ['token_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_token_address'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_source'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_network_id'), table_name='alerts')
    op.drop_index('idx_alerts_active_coingecko', table_name='alerts', postgresql_where=sa.text("alert_type = 'token_price' AND source = 'coingecko'"))
    op.drop_index('idx_alerts_active_cmc', table_name='alerts', postgresql_where=sa.text("alert_type = 'token_price' AND source = 'cmc'"))
    op.create_index('idx_alerts_active_cmc_id', 'alerts', ['is_active', 'cmc_id'], unique=False, postgresql_where="((alert_type)::text = 'token_price'::text)")
    op.alter_column('alerts', 'cmc_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('alerts', 'polling_interval_seconds')
    op.drop_column('alerts', 'network_id')
    op.drop_column('alerts', 'token_address')
    op.drop_column('alerts', 'source')
    # ### end Alembic commands ###
