"""Align models with DB schema (JSONB, indexes, association obj)

Revision ID: ea62a4ccea69
Revises: 
Create Date: 2025-05-01 23:31:21.332568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea62a4ccea69'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_snapshots',
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('token_balances', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('(portfolio_id IS NOT NULL AND wallet_id IS NULL) OR (portfolio_id IS NULL AND wallet_id IS NOT NULL) OR (portfolio_id IS NULL AND wallet_id IS NULL)', name='check_snapshot_target'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.wallet_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_index('idx_portfolio_snapshots_portfolio_id', 'portfolio_snapshots', ['portfolio_id'], unique=False)
    op.create_index('idx_portfolio_snapshots_timestamp', 'portfolio_snapshots', ['timestamp'], unique=False)
    op.create_index('idx_portfolio_snapshots_user_id', 'portfolio_snapshots', ['user_id'], unique=False)
    op.create_index('idx_portfolio_snapshots_wallet_id', 'portfolio_snapshots', ['wallet_id'], unique=False)
    op.create_index('idx_snapshot_user_target_time', 'portfolio_snapshots', ['user_id', 'portfolio_id', 'wallet_id', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_portfolio_id'), 'portfolio_snapshots', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_timestamp'), 'portfolio_snapshots', ['timestamp'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_user_id'), 'portfolio_snapshots', ['user_id'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_wallet_id'), 'portfolio_snapshots', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_alerts_portfolio_id'), 'alerts', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_alerts_tracked_wallet_id'), 'alerts', ['tracked_wallet_id'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_index(op.f('ix_alerts_wallet_id'), 'alerts', ['wallet_id'], unique=False)
    op.drop_constraint('portfolios_user_id_name_key', 'portfolios', type_='unique')
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_portfolio_name', 'portfolios', ['user_id', 'name'])
    op.drop_constraint('tracked_wallets_user_id_address_key', 'tracked_wallets', type_='unique')
    op.create_index(op.f('ix_tracked_wallets_address'), 'tracked_wallets', ['address'], unique=False)
    op.create_index(op.f('ix_tracked_wallets_user_id'), 'tracked_wallets', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_tracked_wallet_address', 'tracked_wallets', ['user_id', 'address'])
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_constraint('wallets_user_id_address_key', 'wallets', type_='unique')
    op.create_index(op.f('ix_wallets_address'), 'wallets', ['address'], unique=False)
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_wallet_address', 'wallets', ['user_id', 'address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_wallet_address', 'wallets', type_='unique')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_address'), table_name='wallets')
    op.create_unique_constraint('wallets_user_id_address_key', 'wallets', ['user_id', 'address'])
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_constraint('uq_user_tracked_wallet_address', 'tracked_wallets', type_='unique')
    op.drop_index(op.f('ix_tracked_wallets_user_id'), table_name='tracked_wallets')
    op.drop_index(op.f('ix_tracked_wallets_address'), table_name='tracked_wallets')
    op.create_unique_constraint('tracked_wallets_user_id_address_key', 'tracked_wallets', ['user_id', 'address'])
    op.drop_constraint('uq_user_portfolio_name', 'portfolios', type_='unique')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.create_unique_constraint('portfolios_user_id_name_key', 'portfolios', ['user_id', 'name'])
    op.drop_index(op.f('ix_alerts_wallet_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_tracked_wallet_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_portfolio_id'), table_name='alerts')
    op.drop_index(op.f('ix_portfolio_snapshots_wallet_id'), table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_user_id'), table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_timestamp'), table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_portfolio_id'), table_name='portfolio_snapshots')
    op.drop_index('idx_snapshot_user_target_time', table_name='portfolio_snapshots')
    op.drop_index('idx_portfolio_snapshots_wallet_id', table_name='portfolio_snapshots')
    op.drop_index('idx_portfolio_snapshots_user_id', table_name='portfolio_snapshots')
    op.drop_index('idx_portfolio_snapshots_timestamp', table_name='portfolio_snapshots')
    op.drop_index('idx_portfolio_snapshots_portfolio_id', table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    # ### end Alembic commands ###
